In [2]:
from pylab import *

In [10]:
def Mat_A_inv(Nx,r):
    A = zeros((Nx,Nx))
    dd , m_r = 2*(1+r) , -r
    for i in range(Nx-1):
        A[i,i] = dd
        A[i+1,i] = m_r
        A[i,i+1] = m_r
    A[-1,-1] = dd
    A_inv = inv(A)
    return A,A_inv

In [18]:
A,A_inv = Mat_A_inv(4,2)
A,A_inv

(array([[ 6., -2.,  0.,  0.],
        [-2.,  6., -2.,  0.],
        [ 0., -2.,  6., -2.],
        [ 0.,  0., -2.,  6.]]),
 array([[0.19090909, 0.07272727, 0.02727273, 0.00909091],
        [0.07272727, 0.21818182, 0.08181818, 0.02727273],
        [0.02727273, 0.08181818, 0.21818182, 0.07272727],
        [0.00909091, 0.02727273, 0.07272727, 0.19090909]]))

In [22]:
print(dot(A,A_inv) )

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.77555756e-17  0.00000000e+00  1.00000000e+00 -5.55111512e-17]
 [-6.93889390e-18  0.00000000e+00 -5.55111512e-17  1.00000000e+00]]
