In [1]:
from pylab import *
from scipy.sparse import *

In [19]:
A_normal = array( [ [1,0,0] , [0,0,3] , [0,7,0] ])
A_normal

array([[1, 0, 0],
       [0, 0, 3],
       [0, 7, 0]])

In [26]:
A_normal*A_normal

array([[ 1,  0,  0],
       [ 0,  0,  9],
       [ 0, 49,  0]])

In [20]:
dot(A_normal,A_normal)

array([[ 1,  0,  0],
       [ 0, 21,  0],
       [ 0,  0, 21]])

In [14]:
A = csr_matrix( [ [1,0,0] , [0,0,3] , [0,7,0] ])
A*A

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [21]:
A.toarray()

array([[1, 0, 0],
       [0, 0, 3],
       [0, 7, 0]])

In [17]:
B = A*A
B.toarray()

array([[ 1,  0,  0],
       [ 0, 21,  0],
       [ 0,  0, 21]])

In [24]:
B = A.toarray()*A.toarray()
B

array([[ 1,  0,  0],
       [ 0,  0,  9],
       [ 0, 49,  0]])

In [22]:
C = dot(A,A)
C.toarray()

array([[ 1,  0,  0],
       [ 0, 21,  0],
       [ 0,  0, 21]])

In [23]:
A

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [28]:
A = csr_matrix( [ [1,0,0] , [0,0,3] , [0,7,0] ])
A2 = csr_matrix( [ [0,1,0] , [3,0,0] , [0,0,7] ])
(A*A2).toarray()

array([[ 0,  1,  0],
       [ 0,  0, 21],
       [21,  0,  0]])

In [29]:
dot(A.toarray(),A2.toarray())

array([[ 0,  1,  0],
       [ 0,  0, 21],
       [21,  0,  0]])

In [30]:
A.toarray()*A2.toarray()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
A3=identity(5)
A3

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements (1 diagonals) in DIAgonal format>