In [1]:
from pylab import *
from scipy.sparse import *
from scipy.sparse.linalg import *

In [2]:
def Mat_A(x_in,r):
    N = len(x_in)
    A = zeros((N,N))
    for i in range(N-1):
        A[i,i] = 2*(1+r)
        A[i,i+1] = -r #diagonal superior
        A[i+1,i] = -r #diagonal inferior
    A[-1,-1] = 2*(1+r)
    return A

In [3]:
x = linspace(0,1,5)
A_normal = Mat_A(x[1:-1],1)
A_normal

array([[ 4., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  4.]])

In [4]:
A_sparse = csr_matrix(A_normal)
A_sparse.toarray()

array([[ 4., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  4.]])

In [5]:
A_sparse

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [6]:
A_diags = diags([-1,4,1],[-1,0,1],shape=(3,3))
A_diags.toarray()

array([[ 4.,  1.,  0.],
       [-1.,  4.,  1.],
       [ 0., -1.,  4.]])

In [7]:
def Mat_A_sparse(x_in,r):
    N = len(x_in)
    A = diags([-r,2*(1+r),-r],[-1,0,1],shape=(N,N))
    return A

In [8]:
x = linspace(0,1,9)
A_ds = Mat_A_sparse(x[1:-1],0.5)
A_ds

<7x7 sparse matrix of type '<class 'numpy.float64'>'
	with 19 stored elements (3 diagonals) in DIAgonal format>

In [9]:
A_ds.toarray()

array([[ 3. , -0.5,  0. ,  0. ,  0. ,  0. ,  0. ],
       [-0.5,  3. , -0.5,  0. ,  0. ,  0. ,  0. ],
       [ 0. , -0.5,  3. , -0.5,  0. ,  0. ,  0. ],
       [ 0. ,  0. , -0.5,  3. , -0.5,  0. ,  0. ],
       [ 0. ,  0. ,  0. , -0.5,  3. , -0.5,  0. ],
       [ 0. ,  0. ,  0. ,  0. , -0.5,  3. , -0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. , -0.5,  3. ]])

In [10]:
C = inv(csc_matrix(A_ds))

In [11]:
dot(C,A_ds).toarray()

array([[ 1.00000000e+00,  0.00000000e+00, -3.46944695e-18,
         8.67361738e-19,  1.08420217e-19, -2.71050543e-20,
         0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00, -2.77555756e-17,
         0.00000000e+00,  8.67361738e-19, -1.08420217e-19,
         2.71050543e-20],
       [-6.93889390e-18,  2.51534904e-17,  1.00000000e+00,
         0.00000000e+00,  3.46944695e-18, -8.67361738e-19,
         1.08420217e-19],
       [-8.67361738e-19, -3.25260652e-19,  3.90312782e-17,
         1.00000000e+00,  2.77555756e-17, -3.46944695e-18,
         0.00000000e+00],
       [-2.16840434e-19, -1.89735380e-19,  3.90312782e-18,
        -1.90819582e-17,  1.00000000e+00, -2.77555756e-17,
         0.00000000e+00],
       [-2.71050543e-20,  5.08219768e-20,  4.87890978e-19,
        -3.03576608e-18,  1.21430643e-17,  1.00000000e+00,
         0.00000000e+00],
       [-3.38813179e-21,  3.55753838e-20, -6.09863722e-20,
         6.77626358e-19, -7.15573434e-18, -1.73472348e-18,
         1.0000000